#!/run/current-system/sw/bin/bash
baseDir=$(readlink -f $(dirname $0)) # pwd of shell script
nixosConfigPath=/etc/nixos
# local nixosPath = /etc/nixos
hard-link-recursive() {
    local srcDir=$1
    local destDir=$2
    local nixFiles=$(find $srcDir -maxdepth 1 -type f -not -name "*.md" -a -not -name ".*" -a  -name "*\.*")
    if [ !  -d ${destDir} ]; then
        echo "Creating directory: $destDir"
        sudo mkdir ${destDir}
    fi
    # echo "linking [ ${basename $nixFiles} ] to $destDir"
    sudo ln -fn $nixFiles ${destDir}   
    local dirs=$(find $srcDir -maxdepth 1 -type d -not -path '*.*' -not -path $srcDir) # all directories except the current one and hidden ones
    for dir in $dirs; do
        hard-link-recursive $dir $destDir/$(basename $dir)
    done
}
echo "This script's parent directory: $baseDir"
echo "Deleting: $nixosConfigPath/* ..."
sudo rm -rf $nixosConfigPath/* # Clear everything in your nixos config and remake.
hard-link-recursive $baseDir $nixosConfigPath
echo "Finished config linking to $nixosConfigPath"

echo "Removing $nixosConfigPath/hardware-configuration.nix..."
sudo rm /etc/nixos/hardware-configuration.nix # remove hardware config
sudo nixos-generate-config # to get your hardware config back
# Parse arguments
UPDATE_FLAKE=no
FLAKE_CONFIG=$NIXOS_FLAKE_CONFIGURATION

for arg in "$@"; do
    if [ "$arg" == "update=yes" ]; then
        UPDATE_FLAKE=yes
    else
        FLAKE_CONFIG=$arg
    fi
done

if [ "$UPDATE_FLAKE" == "yes" ]; then
    echo "Updating flake..."
    sudo nix flake update --flake $nixosConfigPath
fi

# rebuild and switch
echo "Rebuilding and switching to new config using flake configuration: $FLAKE_CONFIG"
sudo nixos-rebuild --show-trace switch --flake $nixosConfigPath/#$FLAKE_CONFIG