# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-b5ac9149-58d9-4164-bbdd-69b46fe9cdc1";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-b5ac9149-58d9-4164-bbdd-69b46fe9cdc1".device = "/dev/disk/by-uuid/b5ac9149-58d9-4164-bbdd-69b46fe9cdc1";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/56D3-30E0";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
