# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-4b7842e1-7ca3-47aa-bd4a-dfc11f17a72e";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-4b7842e1-7ca3-47aa-bd4a-dfc11f17a72e".device = "/dev/disk/by-uuid/4b7842e1-7ca3-47aa-bd4a-dfc11f17a72e";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/24C9-EF68";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
