#!/usr/bin/bash
BASEDIR=$(readlink -f $(dirname $0))/home-manager # pwd of home-manager

hard-link-recursive() {
    local srcDir=$1
    local destDir=$2
    local nixFiles=$(find $srcDir -maxdepth 1 -type f -name "*.nix")
    if [ !  -d ${destDir} ]; then
        echo "creating directory $destDir"
        mkdir ${destDir}
    fi
    echo "copying [ $nixFiles ] to $destDir"
    ln -fn $nixFiles ${destDir}   
    local dirs=$(find $srcDir -maxdepth 1 -type d -not -path '*.*' -not -path $srcDir) # all directories except the current one and hidden ones
    for dir in $dirs; do
        hard-link-recursive $dir $destDir/$(basename $dir)
    done
}
# Clear everything in your nix home-manger config and remake.
echo "Clearing old config..."
rm -rf "${HOME}/.config/home-manager/*"
echo "Script parent dir: $BASEDIR"
echo "Updating nix-channel..."
nix-channel --update
hard-link-recursive $BASEDIR  "${HOME}/.config/home-manager" && \
echo "Linking done. Switching to new config."
home-manager switch