#!/usr/bin/bash
local test='$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )/'
echo "script parent dir: $test"
# Clear everything in your nixos config and remake.
sudo rm -rf /etc/nixos/* 
# sudo ln -fn $(find . -type f | grep .nix ) /etc/nixos

# Hardlink this repo into there.
sudo mkdir /etc/nixos/home-manager && sudo mkdir /etc/nixos/home-manager/configs && \
sudo ln -fn $(find $test -maxdepth 1 -type f -name "*.nix") /etc/nixos && sudo rm /etc/nixos/hardware-configuration.nix && \
sudo ln -fn $(find ${test}home-manager/ -maxdepth 1 -type f -name "*.nix") /etc/nixos/home-manager && \
sudo ln -fn $(find ${test}home-manager/configs -maxdepth 1 -type f -name "*.nix") /etc/nixos/home-manager/configs && \
sudo nixos-generate-config # to get your hardware config back

# rebuild and switch
sudo nixos-rebuild switch