#!/usr/bin/bash
# Clear everything in your nixos config and remake.
sudo rm -rf /etc/nixos/* 
# sudo ln -fn $(find . -type f | grep .nix ) /etc/nixos

# Hardlink this repo into there.
sudo mkdir /etc/nixos/home-manager && sudo mkdir /etc/nixos/home-manager/configs && sudo mkdir /etc/nixos/system && \
sudo ln -fn ./configuration.nix /etc/nixos && \
sudo ln -fn $(find system/ -maxdepth 1 -type f -name "*.nix") /etc/nixos/system && \
sudo ln -fn $(find home-manager/ -maxdepth 1 -type f -name "*.nix") /etc/nixos/home-manager && \
sudo ln -fn $(find home-manager/configs -maxdepth 1 -type f -name "*.nix") /etc/nixos/home-manager/configs && \
sudo nixos-generate-config # to get your hardware config back

# rebuild and switch
sudo nixos-rebuild switch