#!/usr/bin/bash
BASEDIR=$(readlink -f $(dirname $0))/home-manager # pwd of home-manager

hard-link-recursive() {
    local srcDir=$1
    local destDir=$2
    local nixFiles=$(find $srcDir -maxdepth 1 -type f -name "*.nix")
    if [ !  -d ${destDir} ]; then
        mkdir ${destDir}
    fi
    ln -fn $nixFiles ${destDir}   
    local dirs=$(find $srcDir -maxdepth 1 -type d -not -path '*.*' -not -path $srcDir) # all directories except the current one and hidden ones
    for dir in $dirs; do
        hard-link-recursive $dir $destDir/$(basename $dir)
    done
}
# Clear everything in your nix home-manger config and remake.
rm -rf "${HOME}/.config/home-manager/*"
echo "script parent dir: $BASEDIR"

hard-link-recursive $BASEDIR  "${HOME}/.config/home-manager" && \
home-manager switch