#!/usr/bin/bash
# Clear everything in your nixos config and remake.
sudo rm -rf /etc/nixos/* 


# Hardlink this repo into there.
sudo mkdir /etc/nixos/home-manager && sudo mkdir /etc/nixos/home-manager/configs \
sudo ln -fn ./configuration.nix ./nix-alien.nix ./home-manager/home-manager-module.nix \
./home-manager/home.nix /home-manager/configs/xdg.nix /etc/nixos/ && \
sudo nixos-generate-config # to get your hardware config back

# rebuild and switch
sudo nixos-rebuild switch